In [1]:
import numpy as np

In [3]:
B = np.eye(6)
B

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [4]:
arr = [1, 2, 3, 4, 5, 6]
arr[1:3:]

[2, 3]

In [5]:
arr2 = np.array(arr)
arr2[1:3:]

array([2, 3])

In [12]:
arr5 = np.arange(1, 101)
arr5

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [14]:
arr5[[4,57,95]]

array([ 5, 58, 96])

In [17]:
arr6 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr6[0,1]

2

In [19]:
# element greater than 2
arr6[arr6 > 2]

array([3, 4, 5, 6, 7, 8, 9])

In [22]:
# element greater than 2 and less than 9

arr6[(arr6 > 2) & (arr6 < 9)]

array([3, 4, 5, 6, 7, 8])

In [24]:
a = 0 and 2
a

0

In [26]:
b = 2 and 0
b

0

In [28]:
c = 1 and 2
c

2

In [29]:
arr5[3]

4

In [30]:
arr[3] = 100
arr

[1, 2, 3, 100, 5, 6]

In [32]:
np.shares_memory(arr, arr5)

False

In [33]:
arr9 = np.array([1,2,3,4,5,6,7,8,9])
arr10 = arr9

arr10[0] = 100
arr10

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [34]:
arr9

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [35]:
np.shares_memory(arr9, arr10)

True

In [36]:
arr11 = arr9.copy()
np.shares_memory(arr9, arr11)

False

In [39]:
np.random.random(10)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897,
       0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752])

In [40]:
np.random.randint(0, 10, 10)

array([0, 9, 3, 4, 0, 0, 4, 1, 7, 3])

In [41]:
np.random.randint(0, 10, (3,3))

array([[2, 4, 7],
       [2, 4, 8],
       [0, 7, 9]])

In [43]:
np.random.seed(0)
np.random.randint(0, 10, (3,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [44]:
np.random.rand(3,3)

array([[0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

In [48]:
A = np.random.random(3)
A

array([0.5488135 , 0.71518937, 0.60276338])

In [69]:
np.random.seed(100)
B = np.random.random()
B

0.5434049417909654

In [71]:
int_ = np.random.randint(low = 0, high = 10, size = 10)

In [72]:
int_

array([1, 0, 8, 4, 0, 9, 6, 2, 4, 1])

In [74]:
e = np.round(np.random.random(10), 2)
e

array([0.65, 0.14, 0.58, 0.48, 0.39, 0.44, 0.4 , 0.44, 0.03, 0.78])

In [75]:
f = e * 100
f

array([65., 14., 58., 48., 39., 44., 40., 44.,  3., 78.])

In [77]:
g = f.astype(int)
g

array([65, 14, 57, 48, 39, 44, 40, 44,  3, 78])

In [78]:
# date format
np.datetime64('2020-05-01')


numpy.datetime64('2020-05-01')

In [79]:
h = np.arange(np.datetime64('2020-05-01'), np.datetime64('2020-05-10'))
h

array(['2020-05-01', '2020-05-02', '2020-05-03', '2020-05-04',
       '2020-05-05', '2020-05-06', '2020-05-07', '2020-05-08',
       '2020-05-09'], dtype='datetime64[D]')

In [81]:
i = np.arange(np.datetime64('2020-05-01'), np.datetime64('2020-05-10'), 2)
i

array(['2020-05-01', '2020-05-03', '2020-05-05', '2020-05-07',
       '2020-05-09'], dtype='datetime64[D]')

In [86]:
h = np.arange(1,33)
h

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [88]:
h.shape

(32,)

In [99]:
j = h.reshape(4,8)
j

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32]])

In [100]:
np.exp(j)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
        4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06],
       [2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
        1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10],
       [7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
        3.93133430e+12, 1.06864746e+13, 2.90488497e+13, 7.89629602e+13]])

In [102]:
k = h.T
k

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [104]:
np.dot(h,k)

11440