In [20]:
print("hello")

hello


In [ ]:
for i in range(0, 10):
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 

In [21]:
import pandas as pd
import numpy as np


In [ ]:
arr = np.array(['a','b','c','d','e','f','g','h','i','j','k'])
print(arr)

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k']


In [ ]:
x = pd.Series(arr)
print(x)

0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
dtype: object


In [ ]:
data = np.array(['a', 'b', 'c'])
x= pd.Series(data)
print(x)

0    a
1    b
2    c
dtype: object


In [ ]:
print(type(x))

<class 'pandas.core.series.Series'>


In [ ]:
d = np.array(['a', 'b', 'c'])
out =  pd.Series(d, index = [100,101,102])
print(out)

100    a
101    b
102    c
dtype: object


In [ ]:
out

100    a
101    b
102    c
dtype: object

In [ ]:
data = {
    'a' : 1,
    'b': 2,
    'c': 3
}

s = pd.Series(data)
s

a    1
b    2
c    3
dtype: int64

In [ ]:
s['a']

1

In [ ]:
type(s)

pandas.core.series.Series

In [ ]:
s = pd.Series(5, index = [0,1,2,3,4,5,6,7,8])
s

0    5
1    5
2    5
3    5
4    5
5    5
6    5
7    5
8    5
dtype: int64

In [ ]:
data = [1,2,3,4,5,6,7,8,9,10,11]
s = pd.Series(5, index = [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])
s

101    5
102    5
103    5
104    5
105    5
106    5
107    5
108    5
109    5
110    5
111    5
dtype: int64

In [ ]:
data = np.array(['Ajlal', 'Anas', 'Dheeraj'])
s = pd.Series(data)
s[1]

'Anas'

In [ ]:
data = [1,2,3,4,5,6,7,8,9,10,11]
s = pd.Series(data, index = [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])
s

101     1
102     2
103     3
104     4
105     5
106     6
107     7
108     8
109     9
110    10
111    11
dtype: int64

In [ ]:
s[101]

1

In [ ]:
data = [1,2,3,4,5,6,7,8,9,10,11]
df = pd.DataFrame(data)
print(df)

     0
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
10  11


In [19]:
data = {
    'a' : 1,
    'b': 2,
    'c': 3
}
df = pd.DataFrame(data)
print(df)

ValueError: If using all scalar values, you must pass an index

In [ ]:
name = ['Ajlal', 'Anas', 'Ravi']
age = [20,25,30]

data = {
'Name': name,
'Age': age
}
print(data)

df = pd.DataFrame(data)
df

{'Name': ['Ajlal', 'Anas', 'Ravi'], 'Age': [20, 25, 30]}


Name  Age
0  Ajlal   20
1   Anas   25
2   Ravi   30

In [35]:
dict1 = {
    "name" : ["Ajlal", "Anas", "Ajlal", "Dheeraj", "Rahul", "Rohit", "Raj", "Rajesh", "Ramesh", "Rajat"],
    "marks" : [99,94,96,94, 87, 98, 78, 67, 89, 90]
}

df = pd.DataFrame(dict1)
df



name  marks
0    Ajlal     99
1     Anas     94
2    Ajlal     96
3  Dheeraj     94
4    Rahul     87
5    Rohit     98
6      Raj     78
7   Rajesh     67
8   Ramesh     89
9    Rajat     90

In [36]:

# print whose marks is greater than 60
df[df['marks']>60]

name  marks
0    Ajlal     99
1     Anas     94
2    Ajlal     96
3  Dheeraj     94
4    Rahul     87
5    Rohit     98
6      Raj     78
7   Rajesh     67
8   Ramesh     89
9    Rajat     90

In [37]:
# create a new dataframe with name and marks as column from previous dataframe and sort ot the unique name from it

df1 = df[['name', 'marks']]
df1


name  marks
0    Ajlal     99
1     Anas     94
2    Ajlal     96
3  Dheeraj     94
4    Rahul     87
5    Rohit     98
6      Raj     78
7   Rajesh     67
8   Ramesh     89
9    Rajat     90

In [54]:
df1.sort_values('name', ascending = True)

# df1.drop_duplicates(subset = 'name', keep = 'first', inplace = True)


name  marks
0    Ajlal     99
1     Anas     94
3  Dheeraj     94
4    Rahul     87
6      Raj     78
9    Rajat     90
7   Rajesh     67
8   Ramesh     89
5    Rohit     98

In [2]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.outer(a, b)
print(c)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
