In [3]:
import numpy as np

In [2]:
np.zeros((4,4), dtype=np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [3]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.ones_like(arr)

array([[1, 1, 1],
       [1, 1, 1]])

In [5]:
matrix = np.full((3, 4), 4)
matrix


array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])